### ISSUE TITLE
Error running Lambda

### ISSUE THREAD

**Issue by mebibou** [PauloGoncalvesBH/running-playwright-on-aws-lambda#5]
When trying to deploy and run the lambda function, I get this error:
```
START RequestId: 72ab12f1-edca-4cdf-bb21-b41804c9337b Version: $LATEST
RequestId: 72ab12f1-edca-4cdf-bb21-b41804c9337b Error: fork/exec node_modules/.bin/aws-lambda-ric: exec format error
Runtime.InvalidEntrypoint
END RequestId: 72ab12f1-edca-4cdf-bb21-b41804c9337b
REPORT RequestId: 72ab12f1-edca-4cdf-bb21-b41804c9337b	Duration: 2.82 ms	Billed Duration: 3 ms	Memory Size: 1024 MB	Max Memory Used: 2 MB	
```
Is there more configuration needed?

**Comment by mebibou** [comment]
Found a solution, in case anyones happens to have the same problem when deploying on Apple M1, need to add the platform here:
```
ecr:
    images:
      baseimage:
        path: ./
        file: Dockerfile
        platform: linux/amd64
```
